### ISSUE TITLE
Error con cognito

### ISSUE THREAD

**Issue by adasoftgt** [adasoftgt/aps-app#4]
Unauthenticated access is not supported for this identity pool.
NotAuthorizedException: Unauthenticated access is not supported for this identity pool.
    at parseJsonError (http://localhost:3000/static/js/bundle.js:615218:17)
    at async getIdDeserializer (http://localhost:3000/static/js/bundle.js:613825:19)
    at async generateIdentityId (http://localhost:3000/static/js/bundle.js:606511:4)
    at async cognitoIdentityIdProvider (http://localhost:3000/static/js/bundle.js:606495:13)
    at async CognitoAWSCredentialsAndIdentityIdProvider.getCredentialsAndIdentityId (http://localhost:3000/static/js/bundle.js:606672:24)
    at async AuthClass.fetchAuthSession (http://localhost:3000/static/js/bundle.js:615950:34)
    at async http://localhost:3000/static/js/bundle.js:23225:35
    
    Reparar este error

**Comment by adasoftgt** [comment]
Este error sale cuanodo no se esta logueado

**Comment by adasoftgt** [comment]
Se encuentra en AuthContext.js:93

**Comment by adasoftgt** [comment]
Se cerro utilizando try para capturar el error de usuario no legueado y utilizar la variable de token de usuario de coginito para no cargar incecesariamente la lista  de roles
